import java.util.Scanner;

public class App {
    public static void main(String[] args) throws Exception {
        Scanner input=new Scanner(System.in);
        System.out.println("Livro Infantil 1");
       System.out.println("Digite o tipo de capa do livro:");
        String capa = input.nextLine();
        System.out.println("Digite o nome do livro:");
        String nome_livro=input.nextLine();
        System.out.println("Digite o nome do autor:");
        String nome_autor = input.nextLine();
        System.out.printf("Digite o ano que o livro foi escrito:");
        int ano_escrito = input.nextInt();
        System.out.println("Digite o genero literário:");
        String genero = input.nextLine();
        System.out.println("Digite o tipo de linguagem:");
        String linguagem = input.nextLine();
        System.out.printf("Digite o ano que foi publicado:");
        int ano_publicado = input.nextInt();
        System.out.println("Digite a data que o livro foi pego:");
        String data_pegoulivro = input.nextLine();
        System.out.println("Digite a data que foi devolvido:");
        String data_devolucao = input.nextLine();
        System.out.println("Digite o nome do leitor");
         String nome_leitor = input.nextLine();
         System.out.println("Digite o email do leitor:");
         String email=input.nextLine();
         System.out.println("Digite o telefone do leitor:");
         String telefone=input.nextLine();
        System.out.println("Digite a sua opiniao sobre o livro");
         String feedback = input.nextLine();
        
       System.out.println("Tipo de capa dp livro:" +capa);
       System.out.println("O nome do livro:"+nome_livro);
       System.out.println("O nome do autor:"+nome_autor);
       System.out.println("O ano que o livro foi escrito:"+ano_escrito);
       System.out.println("O genero literáro:"+genero);
       System.out.println("O tipo de linguagem:"+linguagem);
       System.out.println("O ano que foi publicado:"+ano_publicado);
       System.out.println("A data que o livro foi pego:"+data_pegoulivro);
       System.out.println("A data que o livro foi devolvido:"+data_devolucao);
       System.out.println("O nome do leitor:"+nome_leitor);
       System.out.println("Opiniao sobre o livro:"+feedback);
        System.out.println("O genero literáro:"+email);
        System.out.println("O genero literáro:"+telefone);

 System.out.println("Livro Infantil 2");
       System.out.println("Digite o tipo de capa do livro:");
        String capa1 = input.nextLine();
        System.out.println("Digite o nome do livro:");
        String nome_livro1=input.nextLine();
        System.out.println("Digite o nome do autor:");
        String nome_autor1 = input.nextLine();
        System.out.printf("Digite o ano que o livro foi escrito:");
        int ano_escrito1 = input.nextInt();
        System.out.println("Digite o genero literário:");
        String genero1 = input.nextLine();
        System.out.println("Digite o tipo de linguagem:");
        String linguagem1 = input.nextLine();
        System.out.printf("Digite o ano que foi publicado:");
        int ano_publicado1 = input.nextInt();
        System.out.println("Digite a data que o livro foi pego:");
        String data_pegoulivro1 = input.nextLine();
        System.out.println("Digite a data que foi devolvido:");
        String data_devolucao1 = input.nextLine();
        System.out.println("Digite o nome do leitor");
         String nome_leitor1 = input.nextLine();
         System.out.println("Digite o email do leitor:");
         String email1=input.nextLine();
         System.out.println("Digite o telefone do leitor:");
         String telefone1=input.nextLine();
        System.out.println("Digite a sua opiniao sobre o livro");
         String feedback1= input.nextLine();
        
       System.out.println("Tipo de capa dp livro:" +capa1);
       System.out.println("O nome do livro:"+nome_livro1);
       System.out.println("O nome do autor:"+nome_autor1);
       System.out.println("O ano que o livro foi escrito:"+ano_escrito1);
       System.out.println("O genero literáro:"+genero1);
       System.out.println("O tipo de linguagem:"+linguagem1);
       System.out.println("O ano que foi publicado:"+ano_publicado1);
       System.out.println("A data que o livro foi pego:"+data_pegoulivro1);
       System.out.println("A data que o livro foi devolvido:"+data_devolucao1);
       System.out.println("O nome do leitor:"+nome_leitor1);
       System.out.println("Opiniao sobre o livro:"+feedback1);
       System.out.println("O genero literáro:"+email1);
       System.out.println("O genero literáro:"+telefone1);

       System.out.println("Livro Infantil 3");
       System.out.println("Digite o tipo de capa do livro:");
        String capa2 = input.nextLine();
        System.out.println("Digite o nome do livro:");
        String nome_livro2=input.nextLine();
        System.out.println("Digite o nome do autor:");
        String nome_autor2= input.nextLine();
        System.out.printf("Digite o ano que o livro foi escrito:");
        int ano_escrito2 = input.nextInt();
        System.out.println("Digite o genero literário:");
        String genero2 = input.nextLine();
        System.out.println("Digite o tipo de linguagem:");
        String linguagem2 = input.nextLine();
        System.out.printf("Digite o ano que foi publicado:");
        int ano_publicado2 = input.nextInt();
        System.out.println("Digite a data que o livro foi pego:");
        String data_pegoulivro2 = input.nextLine();
        System.out.println("Digite a data que foi devolvido:");
        String data_devolucao2 = input.nextLine();
        System.out.println("Digite o nome do leitor");
         String nome_leitor2 = input.nextLine();
         System.out.println("Digite o email do leitor:");
         String email2=input.nextLine();
         System.out.println("Digite o telefone do leitor:");
         String telefone2=input.nextLine();
        System.out.println("Digite a sua opiniao sobre o livro");
         String feedback2 = input.nextLine();
        
       System.out.println("Tipo de capa dp livro:" +capa2);
       System.out.println("O nome do livro:"+nome_livro2);
       System.out.println("O nome do autor:"+nome_autor2);
       System.out.println("O ano que o livro foi escrito:"+ano_escrito2);
       System.out.println("O genero literáro:"+genero2);
       System.out.println("O tipo de linguagem:"+linguagem2);
       System.out.println("O ano que foi publicado:"+ano_publicado2);
       System.out.println("A data que o livro foi pego:"+data_pegoulivro2);
       System.out.println("A data que o livro foi devolvido:"+data_devolucao2);
       System.out.println("O nome do leitor:"+nome_leitor2);
       System.out.println("Opiniao sobre o livro:"+feedback2);
       System.out.println("O genero literáro:"+email2);
        System.out.println("O genero literáro:"+telefone2);
        

       System.out.println("Livro Cristao 1");
       System.out.println("Digite o tipo de capa do livro:");
        String capa3 = input.nextLine();
        System.out.println("Digite o nome do livro:");
        String nome_livro3=input.nextLine();
        System.out.println("Digite o nome do autor:");
        String nome_autor3 = input.nextLine();
        System.out.printf("Digite o ano que o livro foi escrito:");
        int ano_escrito3 = input.nextInt();
        System.out.println("Digite o genero literário:");
        String genero3 = input.nextLine();
        System.out.println("Digite a base biblica:");
        String basebiblica = input.nextLine();
        System.out.printf("Digite o ano que foi publicado:");
        int ano_publicado3 = input.nextInt();
        System.out.println("Digite a data que o livro foi pego:");
        String data_pegoulivro3 = input.nextLine();
        System.out.println("Digite a data que foi devolvido:");
        String data_devolucao3 = input.nextLine();
        System.out.println("Digite o nome do leitor");
         String nome_leitor3 = input.nextLine();
         System.out.println("Digite o email do leitor:");
        String email3=input.nextLine();
        System.out.println("Digite o telefone do leitor:");
        String telefone3=input.nextLine();
        System.out.println("Digite a sua opiniao sobre o livro");
         String feedback3 = input.nextLine();
        
       System.out.println("Tipo de capa dp livro:" +capa3);
       System.out.println("O nome do livro:"+nome_livro3);
       System.out.println("O nome do autor:"+nome_autor3);
       System.out.println("O ano que o livro foi escrito:"+ano_escrito3);
       System.out.println("O genero literáro:"+genero3);
       System.out.println("O tipo de linguagem:"+basebiblica);
       System.out.println("O ano que foi publicado:"+ano_publicado3);
       System.out.println("A data que o livro foi pego:"+data_pegoulivro3);
       System.out.println("A data que o livro foi devolvido:"+data_devolucao3);
       System.out.println("O nome do leitor:"+nome_leitor3);
       System.out.println("Opiniao sobre o livro:"+feedback3);
       System.out.println("O genero literáro:"+email3);
        System.out.println("O genero literáro:"+telefone3);

       System.out.println("Livro Cristao 2");
       System.out.println("Digite o tipo de capa do livro:");
        String capa4 = input.nextLine();
        System.out.println("Digite o nome do livro:");
        String nome_livro4=input.nextLine();
        System.out.println("Digite o nome do autor:");
        String nome_autor4 = input.nextLine();
        System.out.printf("Digite o ano que o livro foi escrito:");
        int ano_escrito4 = input.nextInt();
        System.out.println("Digite o genero literário:");
        String genero4 = input.nextLine();
        System.out.println("Digite a base biblica:");
        String basebiblica1 = input.nextLine();
        System.out.printf("Digite o ano que foi publicado:");
        int ano_publicado4 = input.nextInt();
        System.out.println("Digite a data que o livro foi pego:");
        String data_pegoulivro4 = input.nextLine();
        System.out.println("Digite a data que foi devolvido:");
        String data_devolucao4 = input.nextLine();
        System.out.println("Digite o nome do leitor");
         String nome_leitor4 = input.nextLine();
        System.out.println("Digite a sua opiniao sobre o livro");
         String feedback4 = input.nextLine();
         System.out.println("Digite o email do leitor:");
        String email4=input.nextLine();
        System.out.println("Digite o telefone do leitor:");
        String telefone4=input.nextLine();
       System.out.println("Tipo de capa dp livro:" +capa4);
       System.out.println("O nome do livro:"+nome_livro4);
       System.out.println("O nome do autor:"+nome_autor4);
       System.out.println("O ano que o livro foi escrito:"+ano_escrito4);
       System.out.println("O genero literáro:"+genero4);
       System.out.println("O tipo de linguagem:"+basebiblica1);
       System.out.println("O ano que foi publicado:"+ano_publicado4);
       System.out.println("A data que o livro foi pego:"+data_pegoulivro4);
       System.out.println("A data que o livro foi devolvido:"+data_devolucao4);
       System.out.println("O nome do leitor:"+nome_leitor4);
       System.out.println("Opiniao sobre o livro:"+feedback4);
       System.out.println("O genero literáro:"+email4);
       System.out.println("O genero literáro:"+telefone4);

       System.out.println("Livro Cristao 3");
       System.out.println("Digite o tipo de capa do livro:");
        String capa5 = input.nextLine();
        System.out.println("Digite o nome do livro:");
        String nome_livro5=input.nextLine();
        System.out.println("Digite o nome do autor:");
        String nome_autor5 = input.nextLine();
        System.out.printf("Digite o ano que o livro foi escrito:");
        int ano_escrito5 = input.nextInt();
        System.out.println("Digite o genero literário:");
        String genero5= input.nextLine();
        System.out.println("Digite a base biblica:");
        String basebiblica2 = input.nextLine();
        System.out.printf("Digite o ano que foi publicado:");
        int ano_publicado5 = input.nextInt();
        System.out.println("Digite a data que o livro foi pego:");
        String data_pegoulivro5 = input.nextLine();
        System.out.println("Digite a data que foi devolvido:");
        String data_devolucao5 = input.nextLine();
        System.out.println("Digite o nome do leitor");
         String nome_leitor5 = input.nextLine();
         System.out.println("Digite o email do leitor:");
        String email5=input.nextLine();
        System.out.println("Digite o telefone do leitor:");
        String telefone5=input.nextLine();
        System.out.println("Digite a sua opiniao sobre o livro");
         String feedback5= input.nextLine();
        
       System.out.println("Tipo de capa dp livro:" +capa5);
       System.out.println("O nome do livro:"+nome_livro5);
       System.out.println("O nome do autor:"+nome_autor5);
       System.out.println("O ano que o livro foi escrito:"+ano_escrito5);
       System.out.println("O genero literáro:"+genero5);
       System.out.println("O tipo de linguagem:"+basebiblica2);
       System.out.println("O ano que foi publicado:"+ano_publicado5);
       System.out.println("A data que o livro foi pego:"+data_pegoulivro5);
       System.out.println("A data que o livro foi devolvido:"+data_devolucao5);
       System.out.println("O nome do leitor:"+nome_leitor5);
       System.out.println("Opiniao sobre o livro:"+feedback5);
       System.out.println("O genero literáro:"+email5);
        System.out.println("O genero literáro:"+telefone5);

        System.out.println("Livro estudos 1");
        System.out.println("Digite o tipo de capa do livro:");
        String capa6 = input.nextLine();
        System.out.println("Digite o nome do livro:");
        String nome_livro6=input.nextLine();
        System.out.println("Digite o nome do autor:");
        String nome_autor6 = input.nextLine();
        System.out.printf("Digite o ano que o livro foi escrito:");
        int ano_escrito6 = input.nextInt();
        System.out.println("Digite o genero literário:");
        String genero6= input.nextLine();
        System.out.println("Digite os dados cientificos:");
        String dadoscientificos = input.nextLine();
        System.out.printf("Digite o ano que foi publicado:");
        int ano_publicado6 = input.nextInt();
        System.out.println("Digite a data que o livro foi pego:");
        String data_pegoulivro6 = input.nextLine();
        System.out.println("Digite a data que foi devolvido:");
        String data_devolucao6 = input.nextLine();
        System.out.println("Digite o nome do leitor");
         String nome_leitor6 = input.nextLine();
         System.out.println("Digite o email do leitor:");
        String email6=input.nextLine();
        System.out.println("Digite o telefone do leitor:");
        String telefone6=input.nextLine();
        System.out.println("Digite a sua opiniao sobre o livro");
         String feedback6= input.nextLine();
        
       System.out.println("Tipo de capa dp livro:" +capa6);
       System.out.println("O nome do livro:"+nome_livro6);
       System.out.println("O nome do autor:"+nome_autor6);
       System.out.println("O ano que o livro foi escrito:"+ano_escrito6);
       System.out.println("O genero literáro:"+genero6);
       System.out.println("O tipo de linguagem:"+dadoscientificos);
       System.out.println("O ano que foi publicado:"+ano_publicado6);
       System.out.println("A data que o livro foi pego:"+data_pegoulivro6);
       System.out.println("A data que o livro foi devolvido:"+data_devolucao6);
       System.out.println("O nome do leitor:"+nome_leitor6);
       System.out.println("Opiniao sobre o livro:"+feedback6);
       System.out.println("O genero literáro:"+email6);
        System.out.println("O genero literáro:"+telefone6);
System.out.println("Livro estudos 2");
System.out.println("Digite o tipo de capa do livro:");
String capa7= input.nextLine();
System.out.println("Digite o nome do livro:");
String nome_livro7=input.nextLine();
System.out.println("Digite o nome do autor:");
String nome_autor7 = input.nextLine();
System.out.printf("Digite o ano que o livro foi escrito:");
int ano_escrito7 = input.nextInt();
System.out.println("Digite o genero literário:");
String genero7= input.nextLine();
System.out.println("Digite os dados cientificos:");
String dadoscientificos1 = input.nextLine();
System.out.printf("Digite o ano que foi publicado:");
int ano_publicado7 = input.nextInt();
System.out.println("Digite a data que o livro foi pego:");
String data_pegoulivro7 = input.nextLine();
System.out.println("Digite a data que foi devolvido:");
String data_devolucao7 = input.nextLine();
System.out.println("Digite o nome do leitor");
 String nome_leitor7= input.nextLine();
 System.out.println("Digite o email do leitor:");
String email7=input.nextLine();
System.out.println("Digite o telefone do leitor:");
String telefone7=input.nextLine();
System.out.println("Digite a sua opiniao sobre o livro");
 String feedback7= input.nextLine();

System.out.println("Tipo de capa dp livro:" +capa7);
System.out.println("O nome do livro:"+nome_livro7);
System.out.println("O nome do autor:"+nome_autor7);
System.out.println("O ano que o livro foi escrito:"+ano_escrito7);
System.out.println("O genero literáro:"+genero7);
System.out.println("O tipo de linguagem:"+dadoscientificos1);
System.out.println("O ano que foi publicado:"+ano_publicado7);
System.out.println("A data que o livro foi pego:"+data_pegoulivro7);
System.out.println("A data que o livro foi devolvido:"+data_devolucao7);
System.out.println("O nome do leitor:"+nome_leitor7);
System.out.println("Opiniao sobre o livro:"+feedback7);
System.out.println("O genero literáro:"+email7);
System.out.println("O genero literáro:"+telefone7);

System.out.println("Livro estudos 2");
System.out.println("Digite o tipo de capa do livro:");
String capa8= input.nextLine();
System.out.println("Digite o nome do livro:");
String nome_livro8=input.nextLine();
System.out.println("Digite o nome do autor:");
String nome_autor8 = input.nextLine();
System.out.printf("Digite o ano que o livro foi escrito:");
int ano_escrito8 = input.nextInt();
System.out.println("Digite o genero literário:");
String genero8= input.nextLine();
System.out.println("Digite os dados cientificos:");
String dadoscientificos2 = input.nextLine();
System.out.printf("Digite o ano que foi publicado:");
int ano_publicado8 = input.nextInt();
System.out.println("Digite a data que o livro foi pego:");
String data_pegoulivro8 = input.nextLine();
System.out.println("Digite a data que foi devolvido:");
String data_devolucao8 = input.nextLine();
System.out.println("Digite o nome do leitor");
 String nome_leitor8= input.nextLine();
 System.out.println("Digite o email do leitor:");
String email8=input.nextLine();
System.out.println("Digite o telefone do leitor:");
String telefone8=input.nextLine();
System.out.println("Digite a sua opiniao sobre o livro");
 String feedback8= input.nextLine();

System.out.println("Tipo de capa dp livro:" +capa8);
System.out.println("O nome do livro:"+nome_livro8);
System.out.println("O nome do autor:"+nome_autor8);
System.out.println("O ano que o livro foi escrito:"+ano_escrito8);
System.out.println("O genero literáro:"+genero8);
System.out.println("O tipo de linguagem:"+dadoscientificos2);
System.out.println("O ano que foi publicado:"+ano_publicado8);
System.out.println("A data que o livro foi pego:"+data_pegoulivro8);
System.out.println("A data que o livro foi devolvido:"+data_devolucao8);
System.out.println("O nome do leitor:"+nome_leitor8);
System.out.println("Opiniao sobre o livro:"+feedback8);
System.out.println("O genero literáro:"+email8);
System.out.println("O genero literáro:"+telefone8);

    }
}
